# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: miduoduo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='miduoduo.proto',
  package='miduoduo',
  serialized_pb=_b('\n\x0emiduoduo.proto\x12\x08miduoduo\"|\n\x08siteinfo\x12\x0e\n\x06siteid\x18\x01 \x02(\t\x12\x11\n\tmachineid\x18\x02 \x02(\x05\x12\x0c\n\x04xgps\x18\x03 \x02(\x02\x12\x0c\n\x04ygps\x18\x04 \x02(\x02\x12\x0e\n\x06tvalue\x18\x05 \x02(\x02\x12\x0e\n\x06wvalue\x18\x06 \x02(\x02\x12\x11\n\talerttime\x18\x07 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SITEINFO = _descriptor.Descriptor(
  name='siteinfo',
  full_name='miduoduo.siteinfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='siteid', full_name='miduoduo.siteinfo.siteid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='machineid', full_name='miduoduo.siteinfo.machineid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xgps', full_name='miduoduo.siteinfo.xgps', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ygps', full_name='miduoduo.siteinfo.ygps', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tvalue', full_name='miduoduo.siteinfo.tvalue', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wvalue', full_name='miduoduo.siteinfo.wvalue', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alerttime', full_name='miduoduo.siteinfo.alerttime', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['siteinfo'] = _SITEINFO

siteinfo = _reflection.GeneratedProtocolMessageType('siteinfo', (_message.Message,), dict(
  DESCRIPTOR = _SITEINFO,
  __module__ = 'miduoduo_pb2'
  # @@protoc_insertion_point(class_scope:miduoduo.siteinfo)
  ))
_sym_db.RegisterMessage(siteinfo)


# @@protoc_insertion_point(module_scope)
